name: stock-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow
      - numpy
      - pandas
      - scikit-learn
      - tensorflow
      - keras
